### ISSUE TITLE
Does not work with Joi V16

### ISSUE THREAD

**Issue by kevinohara80** [kamronbatman/joi-password-complexity#13]
Using this module with `@hapi/joi@^16` does not work because Joi now checks and throws when multiple versions of Joi are detected. This is because the Joi version is pinned to `15.1.1` in this module.

The error you receive is:

`Error: Cannot mix different versions of joi schemas`

This could be fixed by moving the Joi dependency to a peer dependency.

**Comment by kamronbatman** [comment]
Ref: #11 to fix this. I am sorry I haven't had time to address it.
IIRC, the PR doesn't use a peer dependency, so that still needs to be done too.
