### ISSUE TITLE
Strength of Memorized Secrets

### ISSUE THREAD

**Issue by tristanls** [kamronbatman/joi-password-complexity#18]
> A.5 Summary
> Length and complexity requirements beyond those recommended here [Users should be encouraged to make their passwords as lengthy as they want, within reason.] significantly increase the difficulty of memorized secrets and increase user frustration. As a result, users often work around these restrictions in a way that is counterproductive. Furthermore, other mitigations such as blacklists, secure hashed storage, and rate limiting are more effective at preventing modern brute-force attacks. Therefore, no additional complexity requirements are imposed.

- [NIST Special Publication 800-63B, Appendix A](https://pages.nist.gov/800-63-3/sp800-63b.html#appA)

**Comment by kamronbatman** [comment]
Ok, thanks for the info.
