### ISSUE TITLE
Can't find label

### ISSUE THREAD

**Issue by abdulloooh** [kamronbatman/joi-password-complexity#23]
My error response message looks like 
```"value" should contain at least 1 upper-cased letter```

Can we get to set label of what I want without writing any custom code? like instead of that, I want ```"password" should contain at least 1 upper-cased letter```

**Comment by kamronbatman** [comment]
Yeah good idea, I'll add that when I get some time. If someone wants to submit a PR instead that would be great!

**Comment by abdulloooh** [comment]
> Yeah good idea, I'll add that when I get some time. If someone wants to submit a PR instead that would be great!
