### ISSUE TITLE
Module does not include any js files

### ISSUE THREAD

**Issue by nflaig** [kamronbatman/joi-password-complexity#32]
Hi,

I think there was an issue when the module was published, it does not include any js files

see node_modules

![image](https://user-images.githubusercontent.com/38436224/98953859-7ef14900-24fd-11eb-9131-3dbcde19566b.png)

I am not using `node >= 14` but I don't see how this would be related

Additional information:

```
joi-password-complexity: 5.0.0
node: v12.16.1
npm: 6.14.8
```

**Comment by kamronbatman** [comment]
Thanks! There must have been an issue. I'll rebuild and republish sometime today.

**Comment by kamronbatman** [comment]
@nflaig, I republished as 5.0.1 and deprecated 5.0.0.
Please try it out and let me know if it works!

**Comment by nflaig** [comment]
@kamronbatman Thanks for the fast update

LGTM now

![image](https://user-images.githubusercontent.com/38436224/98984558-a73f6e80-2522-11eb-9ee5-e57df28755dc.png)

**Comment by nflaig** [comment]
@kamronbatman as a side note, does the module really need node > 14?

**Comment by kamronbatman** [comment]
I don't think so. The node version that is supported would be whatever typescript/joi supports. I can make that an official adjustment later. Thanks for flagging that.
