### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by nflaig** [kamronbatman/joi-password-complexity#33]
Hi again,

there is another problem which I didn't test yesterday but when trying to run the application I got the following error:

`SyntaxError: Cannot use import statement outside a module`

in  `node_modules/joi-password-complexity/lib/index.js`  it is trying to use `import` instead of `require`

`import Joi from 'joi';`

this might be due to the [tsconfig.json](https://github.com/kamronbatman/joi-password-complexity/blob/master/tsconfig.json#L12), probably need to change `"module": "esnext"` to `"module": "commonjs"`

Additional information:

```
joi-password-complexity: 5.0.1
node: v12.16.1
npm: 6.14.8
```

**Comment by kamronbatman** [comment]
Ah thanks! I'll make the change tomorrow and fix it.

**Comment by nflaig** [comment]
I can do a PR for this and also run it against the tests in my application to also get proper integration testing.
