### ISSUE TITLE
generic error message 

### ISSUE THREAD

**Issue by 7dev3134** [kamronbatman/joi-password-complexity#4]
the validation work but, when it fail the validation message is always the same

` "message": "\"value\" must meet password complexity requirements",`

is there a way to show a custom message to indicate what is need to change in the password ? 
thanks

**Comment by andreavitiani** [comment]
I have the same question..
`Joi.validate('aPassword123!', new PasswordComplexity(complexityOptions), (err, value) => {
  //...
})`

how can I implement the costume message in my job validation if my code is:

`function validation(user) {
  const schema = Joi.object().keys({
    name: Joi.string()
      .required()
      .min(5)
      .max(50),
    email: Joi.string()
      .required()
      .min(6)
      .max(255)
      .email(),
    password: new PasswordComplexity(complexityOptions).required()
  });
  return Joi.validate(user, schema);
}`
?

For now the only solution I know is implementing a message in front end sign up page

**Comment by Mostalpha7** [comment]
You can do something like this;

password: JoiPasswordComplexity.string().minOfSpecialCharacters(2).minOfLowercase(2).minOfUppercase(2).minOfNumeric(2).messages({
                  "password.minOfUppercase": "my custom error message",
                  "password.minOfLowercase": "my custom error message",
                  "password.minOfSpecialCharacters": "my custom error message",
                  "password.minOfNumeric": "my custom error message",
            }),
