### ISSUE TITLE
installing version 5.0.2 but get forcing to version 5.1.0

### ISSUE THREAD

**Issue by ahsandev2019** [kamronbatman/joi-password-complexity#41]
i got error on version 5.1.0 
         ```
const PasswordComplexity = require('joi-password-complexity').default
         ```

and use at joi like this 

 ```
   password: Joi.string()
              .min(6)
              .required()
              .error(new Error('Password must be contain 1 lowerCase, 1 upperCase & 1 number')),
```
then i got error 
         ```
TypeError: PasswordComplexity is not a function
         ```

then i trying to downgrade version, clear yarn lock, node_modules and yarn chace too, trying download version 5.0.2 but still error
then i check the version at yarn.lock i got this 

```
joi-password-complexity@^5.0.2:
  version "5.1.0"
  resolved "https://registry.yarnpkg.com/joi-password-complexity/-/joi-password-complexity-5.1.0.tgz#7506d3adce429d52c1331910f20fd5f571c273d1"
  integrity sha512-2F/cPybttJGuyVmZ8X/yihemshhAuFt4fHGlz8CFNP7R8PzH90K8OeNzY9RrdADM6uu3D2xTXej/odvRjdkqaw==


```
seem the package forcing me to use 5.1.0

my package list : 
    "joi": "^17.2.0",
    "joi-password-complexity": "^5.0.2",

**Comment by ahsandev2019** [comment]
i forcing by edit yarn.lock and use this , its solved but for new instalation its forcing to use 5.1.0
```

joi-password-complexity@^5.0.2:
  version "5.0.2"
  resolved "https://registry.yarnpkg.com/joi-password-complexity/-/joi-password-complexity-5.0.2.tgz#2bb72de7af695c098bc4e0cdb382b73700e72ae2"
  integrity sha512-KJ9CyPNjPMqmBaNmEhXZX7W5+xkZt7F2CGL1pjWY7f8H6078DPAbtpmNOZ3S/rHHQ3w25DHTupvxyRNtgXHdNA==
```

**Comment by kamronbatman** [comment]
Remove the '^' from the version in package.json. This is called version pinning.

The version 5.1.0 shouldn't require you to put `.default` anymore. Maybe that is the error?

**Comment by ahsandev2019** [comment]
> Remove the '^' from the version in package.json. This is called version pinning.
> 
> The version 5.1.0 shouldn't require you to put `.default` anymore. Maybe that is the error?

fixed with delte .default 
thanks for update it :)
