### ISSUE TITLE
Is the lib being maintained by the developers?

### ISSUE THREAD

**Issue by joaoeliandro** [kamronbatman/joi-password-complexity#51]
I would like to know if this lib continues to be updated and maintained by its contributors?

**Comment by kamronbatman** [comment]
@joaoeliandro, I don't have plans to add features, but I will support it and update it as needed. I also urge the community to help keep it up-to-date as well.

Let me know if you find issues, or if Joi gets an update that requires this plugin to be fixed.

If you have ideas for features, I would love to hear it!

**Comment by joaoeliandro** [comment]
During any installation using yarn, it always shows a warning about peerDependencies with Joi:
` warning "> joi-password-complexity@5.1.0" has unmet peer dependency "joi@>= 17"`

**Comment by kamronbatman** [comment]
Peer dependencies do not get installed automatically. You need to do that yourself.

**Comment by kamronbatman** [comment]
Feel free to open this if you have more questions or if you need help!
