### ISSUE TITLE
requirementCount does not work as expected

### ISSUE THREAD

**Issue by nflaig** [kamronbatman/joi-password-complexity#7]
## Description
The `requirementCount` property is not working as expected. No matter which value is used the behavior is the same. I also noticed that the tests included in this repo only use the `defaultOptions` where the `requirementCount` is `4` which does not catch the issue.

## Code
```javascript
const Joi = require('@hapi/joi');
const PasswordComplexity = require('joi-password-complexity');

const complexityOptions = {
    min: 8,
    max: 30,
    lowerCase: 1,
    upperCase: 1,
    numeric: 1,
    symbol: 1,
    requirementCount: 3,
  }

const { error } = Joi.validate('Password123', new PasswordComplexity(complexityOptions));
```

## Current Behavior
`error.details[0].message == "value" doesn't contain the required symbols `

## Expected Behavior
`error == null`

## Environment
- Windows 10 Version 1803 (Build 17134.885)
- Node.js v10.16.2
- @hapi/joi 15.1.1
- joi-password-complexity 3.0.0

## Acceptance Criteria
- [ ] `requirementCount` should work as expected
- [ ] add tests which use different `requirementCount` values

**Comment by kamronbatman** [comment]
Thank you @nflaig. I fixed it in v3.1.0 and published. Let me know if you still experience issues.

**Comment by nflaig** [comment]
@kamronbatman I reviewed the changes and the additional tests. I also did some manual tests by updating the packages and the issue seems to be solved.

**Comment by kamronbatman** [comment]
Thank you!
