### ISSUE TITLE
Can I use this as part of a larger schema?

### ISSUE THREAD

**Issue by BanovMiroslav** [kamronbatman/joi-password-complexity#9]
I would like to use this as part of a larger schema. For example something like:

```JavaScript
const validatedData = Joi.object().keys(
  email: Joi.string().required().email({ minDomainSegments: 2 }),
  password: Joi.string().required().passwordComplexity(options)
).validate(request.payload, {abortEarly: false});
```
It's a large schema and I use the errors to have in-place messages for every field. I want to use Joi to simplify validation and separate the validation rules from my other logic. But passwords are giving me trouble with Joi v15.1.1.

Is there such an option? Or can you advise some way to do that?

**Comment by mpachin** [comment]
@BanovMiroslav Did you tried [custom validation function](https://hapi.dev/family/joi/?v=16.1.7#anycustommethod-description)? Looks like it should fit this purpose well :)

**Comment by mpachin** [comment]
@BanovMiroslav I've just used this library like this and it's working:

```javascript
Joi.object({
  password: new PasswordComplexity(complexityOptions).required(),
  // ...
})
```
I hope this will help.

**Comment by kamronbatman** [comment]
Let's revisit this after v4 comes out with Joi v16. If it still can work then I'll close this out.

**Comment by kamronbatman** [comment]
@mpachin can you please test v4 to see if it still works for this case?

**Comment by ericlcolvin** [comment]
@kamronbatman I am getting a `PasswordComplexity is not a constructor` error when using it in this case.
hapi 19.0.1
joi 17.0.2
joi-password-complexity 4.0.0

**Comment by BanovMiroslav** [comment]
Just to inform you I have moved on to use custom validation function. Reason is that I wanted to handle other alphabets that aren't just [a-z].

Thanks for the support :). I am OK to close this one.
